const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./src/models/Product');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '.env') });

const products = [
    // --- Ethnic Wear (5 items) ---
    {
        name: "Embroidered Anarkali Kurta",
        description: "Elegant maroon anarkali kurta with gold thread embroidery.",
        price: 3999,
        category: "Ethnic Wear",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Ethnic",
        color: "Maroon",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=800&auto=format&fit=crop"],
        fabric: "Georgette",
        occasion: "Party",
        fit: "Anarkali",
        rating: 4.8,
        numReviews: 42,
        countInStock: 20
    },
    {
        name: "Printed Cotton Saree",
        description: "Lightweight cotton saree with block prints. Blouse piece included.",
        price: 1999,
        category: "Ethnic Wear",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Ethnic",
        color: "Indigo",
        sizes: ["One Size"],
        images: ["https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=800&auto=format&fit=crop"],
        fabric: "Cotton",
        occasion: "Casual",
        fit: "Regular",
        rating: 4.6,
        numReviews: 35,
        countInStock: 30
    },
    {
        name: "Festive Lehenga Choli",
        description: "Stunning pink lehenga choli with mirror work. Perfect for weddings.",
        price: 8999,
        category: "Ethnic Wear",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Ethnic",
        color: "Pink",
        sizes: ["M", "L"],
        images: ["https://images.unsplash.com/photo-1583391724248-e69e068f0295?q=80&w=800&auto=format&fit=crop"],
        fabric: "Silk",
        occasion: "Wedding",
        fit: "Regular",
        rating: 4.9,
        numReviews: 15,
        countInStock: 10
    },
    {
        name: "Silk Blend Palazzo Suit",
        description: "Modern palazzo suit in emerald green with minimal embellishments.",
        price: 4499,
        category: "Ethnic Wear",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Ethnic",
        color: "Green",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1605296830745-77987042537f?q=80&w=800&auto=format&fit=crop"],
        fabric: "Silk Blend",
        occasion: "Party",
        fit: "Regular",
        rating: 4.7,
        numReviews: 28,
        countInStock: 18
    },
    {
        name: "Chikankari Kurti",
        description: "Handcrafted white lucknowi chikankari kurti. Elegant and timeless.",
        price: 2499,
        category: "Ethnic Wear",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Ethnic",
        color: "White",
        sizes: ["XS", "S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1583391724248-e69e068f0295?q=80&w=800&auto=format&fit=crop"], // Placeholder
        fabric: "Cotton",
        occasion: "Casual",
        fit: "Straight",
        rating: 4.8,
        numReviews: 60,
        countInStock: 40
    },

    // --- Skirts (5 items) ---
    {
        name: "Pleated Midi Skirt",
        description: "Elegant pleated midi skirt in metallic gold finish.",
        price: 2599,
        category: "Skirts",
        parentCategory: "women",
        gender: "Women",
        brand: "Evening Muse",
        color: "Gold",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?q=80&w=800&auto=format&fit=crop"],
        fabric: "Polyester",
        occasion: "Party",
        fit: "Regular",
        rating: 4.8,
        numReviews: 75,
        countInStock: 25
    },
    {
        name: "Denim Mini Skirt",
        description: "Classic blue denim mini skirt with distressed details.",
        price: 1899,
        category: "Skirts",
        parentCategory: "women",
        gender: "Women",
        brand: "Denim Co",
        color: "Blue",
        sizes: ["26", "28", "30", "32"],
        images: ["https://images.unsplash.com/photo-1577900232427-18219b916b4f?q=80&w=800&auto=format&fit=crop"],
        fabric: "Denim",
        occasion: "Casual",
        fit: "Regular",
        rating: 4.5,
        numReviews: 90,
        countInStock: 35
    },
    {
        name: "Floral A-Line Skirt",
        description: "Flowy A-line skirt with vibrant floral print.",
        price: 2299,
        category: "Skirts",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Bloom",
        color: "Multicolor",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1548624147-93b4ceb59330?q=80&w=800&auto=format&fit=crop"],
        fabric: "Rayon",
        occasion: "Casual",
        fit: "A-Line",
        rating: 4.6,
        numReviews: 40,
        countInStock: 30
    },
    {
        name: "Pencil Skirt",
        description: "Structured black pencil skirt for office wear.",
        price: 1999,
        category: "Skirts",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Formal",
        color: "Black",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1582142327529-e8542dc21127?q=80&w=800&auto=format&fit=crop"],
        fabric: "Cotton Blend",
        occasion: "Formal",
        fit: "Slim",
        rating: 4.7,
        numReviews: 65,
        countInStock: 25
    },
    {
        name: "Maxi Boho Skirt",
        description: "Long tiered maxi skirt in earth tones.",
        price: 2799,
        category: "Skirts",
        parentCategory: "women",
        gender: "Women",
        brand: "Free Spirit",
        color: "Brown",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1565191993208-8f673894723c?q=80&w=800&auto=format&fit=crop"],
        fabric: "Cotton",
        occasion: "Casual",
        fit: "Relaxed",
        rating: 4.5,
        numReviews: 30,
        countInStock: 20
    },

    // --- Jeans (5 items) ---
    {
        name: "High-Waisted Skinny Jeans",
        description: "Classic high-waisted skinny jeans with stretch.",
        price: 2999,
        category: "Jeans",
        parentCategory: "women",
        gender: "Women",
        brand: "Denim Co",
        color: "Blue",
        sizes: ["26", "28", "30", "32"],
        images: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=800&auto=format&fit=crop"],
        fabric: "Denim",
        occasion: "Casual",
        fit: "Skinny",
        rating: 4.7,
        numReviews: 200,
        countInStock: 60
    },
    {
        name: "Mom Jeans",
        description: "Retro-inspired mom fit jeans for a relaxed look.",
        price: 2799,
        category: "Jeans",
        parentCategory: "women",
        gender: "Women",
        brand: "Retro Vibes",
        color: "Light Blue",
        sizes: ["26", "28", "30", "32"],
        images: ["https://images.unsplash.com/photo-1584370848010-d7cc637703e6?q=80&w=800&auto=format&fit=crop"],
        fabric: "Denim",
        occasion: "Casual",
        fit: "Relaxed",
        rating: 4.5,
        numReviews: 110,
        countInStock: 40
    },
    {
        name: "Black Ripped Skinny Jeans",
        description: "Edgy black skinny jeans with ripped knees.",
        price: 3299,
        category: "Jeans",
        parentCategory: "women",
        gender: "Women",
        brand: "Urban Edge",
        color: "Black",
        sizes: ["26", "28", "30", "32"],
        images: ["https://images.unsplash.com/photo-1560243563-14411142ad1d?q=80&w=800&auto=format&fit=crop"],
        fabric: "Denim",
        occasion: "Casual",
        fit: "Skinny",
        rating: 4.6,
        numReviews: 85,
        countInStock: 30
    },
    {
        name: "White Wide Leg Jeans",
        description: "Chic white wide leg jeans for summer.",
        price: 3499,
        category: "Jeans",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Bloom",
        color: "White",
        sizes: ["26", "28", "30", "32"],
        images: ["https://images.unsplash.com/photo-1595995572621-e04e9eb20576?q=80&w=800&auto=format&fit=crop"],
        fabric: "Denim",
        occasion: "Casual",
        fit: "Wide Leg",
        rating: 4.8,
        numReviews: 50,
        countInStock: 25
    },
    {
        name: "Bootcut Jeans",
        description: "Flattering bootcut jeans with a dark wash.",
        price: 2699,
        category: "Jeans",
        parentCategory: "women",
        gender: "Women",
        brand: "Denim Co",
        color: "Dark Blue",
        sizes: ["26", "28", "30", "32"],
        images: ["https://images.unsplash.com/photo-1577900232427-18219b916b4f?q=80&w=800&auto=format&fit=crop"], // Reuse appropriate image
        fabric: "Denim",
        occasion: "Casual",
        fit: "Bootcut",
        rating: 4.4,
        numReviews: 40,
        countInStock: 35
    },

    // --- Activewear (5 items) ---
    {
        name: "High-Imapct Sports Bra",
        description: "Supportive sports bra for running and high-intensity workouts.",
        price: 1499,
        category: "Activewear",
        parentCategory: "women",
        gender: "Women",
        brand: "Active Life",
        color: "Black",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=800&auto=format&fit=crop"],
        fabric: "Polyester",
        occasion: "Sports",
        fit: "Tight",
        rating: 4.8,
        numReviews: 120,
        countInStock: 50
    },
    {
        name: "Seamless Yoga Leggings",
        description: "Buttery soft seamless leggings for yoga.",
        price: 1999,
        category: "Activewear",
        parentCategory: "women",
        gender: "Women",
        brand: "Active Life",
        color: "Pink",
        sizes: ["XS", "S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1549497557-d54cd5f5fa64?q=80&w=800&auto=format&fit=crop"],
        fabric: "Spandex",
        occasion: "Sports",
        fit: "Skinny",
        rating: 4.9,
        numReviews: 80,
        countInStock: 40
    },
    {
        name: "Running Shorts 2-in-1",
        description: "Performance running shorts with built-in compression inner.",
        price: 1699,
        category: "Activewear",
        parentCategory: "women",
        gender: "Women",
        brand: "Active Life",
        color: "Grey",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1538805060504-d141e4c760cd?q=80&w=800&auto=format&fit=crop"],
        fabric: "Polyester",
        occasion: "Sports",
        fit: "Regular",
        rating: 4.7,
        numReviews: 50,
        countInStock: 35
    },
    {
        name: "Zip-Up Track Jacket",
        description: "Lightweight track jacket for warm-ups and cool-downs.",
        price: 2499,
        category: "Activewear",
        parentCategory: "women",
        gender: "Women",
        brand: "Active Life",
        color: "White",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=800&auto=format&fit=crop"],
        fabric: "Nylon",
        occasion: "Sports",
        fit: "Regular",
        rating: 4.5,
        numReviews: 30,
        countInStock: 25
    },
    {
        name: "Training Tank Top",
        description: "Breathable mesh tank top for intense training sessions.",
        price: 999,
        category: "Activewear",
        parentCategory: "women",
        gender: "Women",
        brand: "Active Life",
        color: "Blue",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1518310383802-640c2de311b2?q=80&w=800&auto=format&fit=crop"],
        fabric: "Polyester",
        occasion: "Sports",
        fit: "Loose",
        rating: 4.6,
        numReviews: 45,
        countInStock: 45
    },

    // --- Dresses (Refresh/Add to Ensure 5+) ---
    {
        name: "Floral Summer Maxi Dress",
        description: "Breezy floral print maxi dress.",
        price: 2999,
        category: "Dresses",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Bloom",
        color: "Pink",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800&auto=format&fit=crop"],
        fabric: "Viscose",
        occasion: "Casual",
        fit: "Relaxed",
        rating: 4.8,
        numReviews: 120,
        countInStock: 45
    },
    {
        name: "Velvet Wrap Dress",
        description: "Luxurious velvet wrap dress in emerald green.",
        price: 5499,
        category: "Dresses",
        parentCategory: "women",
        gender: "Women",
        brand: "Evening Muse",
        color: "Green",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800&auto=format&fit=crop"], // Placeholder
        fabric: "Velvet",
        occasion: "Party",
        fit: "Regular",
        rating: 4.9,
        numReviews: 30,
        countInStock: 15
    },
    {
        name: "Cotton Shirt Dress",
        description: "Smart white cotton shirt dress for casual fridays.",
        price: 2499,
        category: "Dresses",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Formal",
        color: "White",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1594223274512-ad4803739b7c?q=80&w=800&auto=format&fit=crop"], // Placeholder
        fabric: "Cotton",
        occasion: "Formal",
        fit: "Regular",
        rating: 4.6,
        numReviews: 40,
        countInStock: 35
    },
    {
        name: "Sequin Mini Dress",
        description: "Sparkling sequin mini dress for night outs.",
        price: 4999,
        category: "Dresses",
        parentCategory: "women",
        gender: "Women",
        brand: "Urban Chic",
        color: "Silver",
        sizes: ["XS", "S", "M"],
        images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=800&auto=format&fit=crop"],
        fabric: "Polyester",
        occasion: "Party",
        fit: "Slim",
        rating: 4.8,
        numReviews: 60,
        countInStock: 20
    },
    {
        name: "Linen Midi Dress",
        description: "Breathable linen midi dress in neutral tone.",
        price: 3299,
        category: "Dresses",
        parentCategory: "women",
        gender: "Women",
        brand: "Simple Life",
        color: "Beige",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=800&auto=format&fit=crop"],
        fabric: "Linen",
        occasion: "Casual",
        fit: "Relaxed",
        rating: 4.7,
        numReviews: 50,
        countInStock: 40
    },

    // --- Tops (5 items) ---
    {
        name: "Classic White Silk Shirt",
        description: "Luxurious silk shirt.",
        price: 3999,
        category: "Tops",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Formal",
        color: "White",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1598554060856-7d8a348b6745?q=80&w=800&auto=format&fit=crop"],
        fabric: "Silk",
        occasion: "Formal",
        rating: 4.7,
        countInStock: 15
    },
    {
        name: "Graphic Cotton Tee",
        description: "Soft cotton tee with cool graphic.",
        price: 1299,
        category: "Tops",
        parentCategory: "women",
        gender: "Women",
        brand: "Urban Chic",
        color: "Black",
        sizes: ["S", "M", "L", "XL"],
        images: ["https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?q=80&w=800&auto=format&fit=crop"],
        fabric: "Cotton",
        occasion: "Casual",
        rating: 4.5,
        countInStock: 50
    },
    {
        name: "Peplum Top",
        description: "Structured peplum top in pastel blue.",
        price: 1899,
        category: "Tops",
        parentCategory: "women",
        gender: "Women",
        brand: "Aurea Bloom",
        color: "Blue",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1582218084534-1c97a8ec28a8?q=80&w=800&auto=format&fit=crop"], // Placeholder
        fabric: "Polyester",
        occasion: "Casual",
        rating: 4.6,
        countInStock: 30
    },
    {
        name: "Off-Shoulder Blouse",
        description: "Boho style off-shoulder blouse.",
        price: 1599,
        category: "Tops",
        parentCategory: "women",
        gender: "Women",
        brand: "Free Spirit",
        color: "White",
        sizes: ["S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1564257631407-4deb1f99d8b2?q=80&w=800&auto=format&fit=crop"],
        fabric: "Cotton",
        occasion: "Casual",
        rating: 4.5,
        countInStock: 40
    },
    {
        name: "Satin Camisole",
        description: "Elegant satin camisole.",
        price: 1199,
        category: "Tops",
        parentCategory: "women",
        gender: "Women",
        brand: "Evening Muse",
        color: "Beige",
        sizes: ["XS", "S", "M", "L"],
        images: ["https://images.unsplash.com/photo-1618244972963-dbee1a7edc95?q=80&w=800&auto=format&fit=crop"],
        fabric: "Satin",
        occasion: "Party",
        rating: 4.5,
        countInStock: 25
    }
];

const seedComplete = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('MongoDB Connected');

        for (const product of products) {
            await Product.findOneAndUpdate(
                { name: product.name },
                product,
                { upsert: true, new: true }
            );
            console.log(`Seeded: ${product.name}`);
        }

        console.log('All remaining Women categories seeded successfully!');
        process.exit();
    } catch (error) {
        console.error('Error seeding products:', error);
        process.exit(1);
    }
};

seedComplete();
