const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');
const Product = require('./src/models/Product');

dotenv.config({ path: path.join(__dirname, '.env') });

const sneakers = [
    // RUNNING / PERFORMANCE
    {
        name: "Zoom X Pro",
        description: "High performance running shoes with responsive cushioning.",
        price: 8999,
        category: "Sneakers",
        parentCategory: "men", // Unisex usually, but defaulting men/unisex
        gender: "Men",
        brand: "Nike",
        sizes: ["7", "8", "9", "10", "11"],
        color: "Blue",
        fabric: "Mesh",
        fit: "Regular Fit",
        occasion: "Sports",
        sneakerTag: "performance",
        stock: 45,
        rating: 4.8,
        numReviews: 120,
        images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: true
    },
    {
        name: "Ultra Boost Infinity",
        description: "Energy returning boost technology for endless run.",
        price: 12999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Men",
        brand: "Adidas",
        sizes: ["7", "8", "9", "10"],
        color: "Black",
        fabric: "Primeknit",
        fit: "Regular Fit",
        occasion: "Sports",
        sneakerTag: "performance",
        stock: 30,
        rating: 4.9,
        numReviews: 200,
        images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: false
    },
    {
        name: "Gel Kayano 29",
        description: "Stability and comfort for long distance runners.",
        price: 10999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Men",
        brand: "Asics",
        sizes: ["8", "9", "10", "11"],
        color: "Grey",
        fabric: "Mesh",
        fit: "Regular Fit",
        occasion: "Sports",
        sneakerTag: "performance",
        stock: 25,
        rating: 4.7,
        numReviews: 85,
        images: ["https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: false
    },
    {
        name: "Clifton 9",
        description: "Balanced cushioning for smooth everyday running.",
        price: 11999,
        category: "Sneakers",
        parentCategory: "women",
        gender: "Women",
        brand: "Hoka",
        sizes: ["6", "7", "8"],
        color: "White",
        fabric: "Mesh",
        fit: "Regular Fit",
        occasion: "Sports",
        sneakerTag: "performance",
        stock: 20,
        rating: 4.8,
        numReviews: 60,
        images: ["https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: true
    },

    // STREET / CASUAL
    {
        name: "Air Jordan 1 High",
        description: "The iconic sneaker that started it all.",
        price: 16999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Jordan",
        sizes: ["7", "8", "9", "10", "11", "12"],
        color: "Red",
        fabric: "Leather",
        fit: "High Top",
        occasion: "Streetwear",
        sneakerTag: "street",
        stock: 10,
        rating: 5.0,
        numReviews: 500,
        images: ["https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: true
    },
    {
        name: "Dunk Low Retro",
        description: "Classic basketball style built for the streets.",
        price: 9695,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Nike",
        sizes: ["6", "7", "8", "9", "10"],
        color: "Black",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Streetwear",
        sneakerTag: "street",
        stock: 15,
        rating: 4.6,
        numReviews: 320,
        images: ["https://images.unsplash.com/photo-1605348532760-6753d2c43329?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: true
    },
    {
        name: "Yeezy Boost 350",
        description: "Futuristic silhouette with primeknit comfort.",
        price: 22999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Adidas",
        sizes: ["8", "9", "10"],
        color: "Beige",
        fabric: "Primeknit",
        fit: "Low Top",
        occasion: "Streetwear",
        sneakerTag: "street",
        stock: 8,
        rating: 4.9,
        numReviews: 410,
        images: ["https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: false
    },
    {
        name: "Chuck 70 High Top",
        description: "Vintage canvas sneaker essential for every wardrobe.",
        price: 4999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Converse",
        sizes: ["6", "7", "8", "9", "10", "11"],
        color: "Black",
        fabric: "Canvas",
        fit: "High Top",
        occasion: "Casual",
        sneakerTag: "street",
        stock: 100,
        rating: 4.7,
        numReviews: 800,
        images: ["https://images.unsplash.com/photo-1607522370275-f14206c11513?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: true
    },
    {
        name: "Old Skool",
        description: "Skate shoe classic with side stripe.",
        price: 5499,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Vans",
        sizes: ["7", "8", "9", "10"],
        color: "Black",
        fabric: "Canvas",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "street",
        stock: 50,
        rating: 4.6,
        numReviews: 450,
        images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: false
    },
    {
        name: "Club C 85",
        description: "Clean, minimalist retro tennis style.",
        price: 6999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Reebok",
        sizes: ["7", "8", "9", "10"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "seasonal",
        stock: 35,
        rating: 4.5,
        numReviews: 120,
        images: ["https://images.unsplash.com/photo-1589188059966-d39f25c95c8c?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: true
    },

    // SEASONAL / BASKETBALL / OTHERS (Filling to 25)
    {
        name: "Forum Low",
        description: "80s basketball icon revived for today.",
        price: 8599,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Men",
        brand: "Adidas",
        sizes: ["8", "9", "10"],
        color: "Blue",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Streetwear",
        sneakerTag: "seasonal",
        stock: 25,
        rating: 4.4,
        numReviews: 90,
        images: ["https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: true
    },
    {
        name: "Air Max 90",
        description: "Comfort and heritage style with visible air.",
        price: 11499,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Men",
        brand: "Nike",
        sizes: ["7", "8", "9", "10", "11"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "bestseller",
        stock: 40,
        rating: 4.8,
        numReviews: 300,
        images: ["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=800"], // Reuse appropriate
        isBestSeller: true
    },
    {
        name: "NB 550",
        description: "Retro basketball oxford style.",
        price: 12999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "New Balance",
        sizes: ["8", "9", "10"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Streetwear",
        sneakerTag: "street",
        stock: 15,
        rating: 4.7,
        numReviews: 220,
        images: ["https://images.unsplash.com/photo-1620783770629-122b78e8c15a?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: true
    },
    {
        name: "Samba OG",
        description: "The classic football trainer, now a street icon.",
        price: 9999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Adidas",
        sizes: ["7", "8", "9", "10"],
        color: "Black",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "street",
        stock: 20,
        rating: 4.9,
        numReviews: 600,
        images: ["https://images.unsplash.com/photo-1632163459196-7243b9511674?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: true
    },
    {
        name: "Blazer Mid 77",
        description: "Vintage hoops style with modern comfort.",
        price: 8695,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Nike",
        sizes: ["7", "8", "9", "10"],
        color: "White",
        fabric: "Leather",
        fit: "High Top",
        occasion: "Casual",
        sneakerTag: "seasonal",
        stock: 30,
        rating: 4.6,
        numReviews: 140,
        images: ["https://images.unsplash.com/photo-1597045566677-8cf032ed6634?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: false
    },
    {
        name: "Stan Smith",
        description: "Fresh, clean and classic tennis shoe.",
        price: 7999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Adidas",
        sizes: ["6", "7", "8", "9", "10"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "bestseller",
        stock: 60,
        rating: 4.7,
        numReviews: 400,
        images: ["https://images.unsplash.com/photo-1532454556402-27357be5530f?auto=format&fit=crop&q=80&w=800"], // approximate
        isBestSeller: true
    },
    {
        name: "RS-X Efekt",
        description: "Futuristic retro-runner silhouette.",
        price: 9999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Men",
        brand: "Puma",
        sizes: ["8", "9", "10"],
        color: "Multi",
        fabric: "Mesh",
        fit: "Regular Fit",
        occasion: "Streetwear",
        sneakerTag: "seasonal",
        stock: 25,
        rating: 4.5,
        numReviews: 70,
        images: ["https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=800"], // Reuse match
        isNewArrival: false
    },
    {
        name: "327 Retro",
        description: "70s heritage inspired running shoe.",
        price: 8999,
        category: "Sneakers",
        parentCategory: "women",
        gender: "Women",
        brand: "New Balance",
        sizes: ["6", "7", "8"],
        color: "Grey",
        fabric: "Suede",
        fit: "Regular Fit",
        occasion: "Casual",
        sneakerTag: "seasonal",
        stock: 20,
        rating: 4.8,
        numReviews: 110,
        images: ["https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&q=80&w=800"],
        isNewArrival: true
    },
    {
        name: "Slip-On Checkerboard",
        description: "Classic slip-on with iconic checkerboard print.",
        price: 4499,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Vans",
        sizes: ["7", "8", "9", "10"],
        color: "Black",
        fabric: "Canvas",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "bestseller",
        stock: 45,
        rating: 4.7,
        numReviews: 350,
        images: ["https://images.unsplash.com/photo-1560769619-37e7d95393d6?auto=format&fit=crop&q=80&w=800"], // approximate
        isBestSeller: true
    },
    {
        name: "Cali Dream",
        description: "West Coast vibes with a chunky sole.",
        price: 7499,
        category: "Sneakers",
        parentCategory: "women",
        gender: "Women",
        brand: "Puma",
        sizes: ["6", "7", "8"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "street",
        stock: 30,
        rating: 4.6,
        numReviews: 90,
        images: ["https://images.unsplash.com/photo-1544376481-2da24422e648?auto=format&fit=crop&q=80&w=800"], // approximate
        isNewArrival: false
    },
    {
        name: "Classic Leather",
        description: "Sharp, clean style that's always in.",
        price: 5999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Men",
        brand: "Reebok",
        sizes: ["8", "9", "10", "11"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "bestseller",
        stock: 35,
        rating: 4.7,
        numReviews: 180,
        images: ["https://images.unsplash.com/photo-1512374382149-233c42b6a83b?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: false
    },
    {
        name: "Air Force 1 '07",
        description: "Legendary style, refined.",
        price: 8195,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Nike",
        sizes: ["7", "8", "9", "10", "11"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "bestseller",
        stock: 150,
        rating: 4.9,
        numReviews: 1200,
        images: ["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800"], // approximate
        isBestSeller: true
    },
    {
        name: "Superstar",
        description: "The shell toe icon.",
        price: 8999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "Adidas",
        sizes: ["6", "7", "8", "9", "10"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "bestseller",
        stock: 50,
        rating: 4.8,
        numReviews: 650,
        images: ["https://images.unsplash.com/photo-1518002171953-a080ee322e2f?auto=format&fit=crop&q=80&w=800"],
        isBestSeller: true
    },
    {
        name: "9060",
        description: "Distorted 2000s running style.",
        price: 14999,
        category: "Sneakers",
        parentCategory: "men",
        gender: "Unisex",
        brand: "New Balance",
        sizes: ["8", "9", "10", "11"],
        color: "Grey",
        fabric: "Mesh",
        fit: "Chunky",
        occasion: "Streetwear",
        sneakerTag: "street",
        stock: 12,
        rating: 4.7,
        numReviews: 150,
        images: ["https://images.unsplash.com/photo-1627916729962-421714041b6c?auto=format&fit=crop&q=80&w=800"], // approximate
        isNewArrival: true
    },
    {
        name: "V-10",
        description: "Sustainable sneakers made differently.",
        price: 13999,
        category: "Sneakers",
        parentCategory: "women",
        gender: "Women",
        brand: "Veja",
        sizes: ["6", "7", "8"],
        color: "White",
        fabric: "Leather",
        fit: "Low Top",
        occasion: "Casual",
        sneakerTag: "seasonal",
        stock: 20,
        rating: 4.6,
        numReviews: 75,
        images: ["https://images.unsplash.com/photo-1606757656910-a29ab4bc270d?auto=format&fit=crop&q=80&w=800"], // approximate
        isNewArrival: false
    }

];

const connectDB = async () => {
    try {
        const conn = await mongoose.connect(process.env.MONGO_URI);
        console.log(`MongoDB Connected: ${conn.connection.host}`);
    } catch (err) {
        console.error(`Error: ${err.message}`);
        process.exit(1);
    }
};

const seedProducts = async () => {
    try {
        await connectDB();

        let addedCount = 0;
        for (const product of sneakers) {
            const result = await Product.findOneAndUpdate(
                { name: product.name },
                product,
                { new: true, upsert: true }
            );
            addedCount++;
        }

        console.log(`Imported ${addedCount} new Sneakers!`);
        process.exit();
    } catch (err) {
        console.error(`${err}`);
        process.exit(1);
    }
};

seedProducts();
